# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric (https://fabricmc.net) mod build properties
# Mod Properties
mod_version=1.0.0
maven_group=com.spideysense
archives_base_name=spidey-sense-mod

# Dependencies (check for latest versions: https://modmuss50.me/fabric.html)
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.14.21

#Fabric api
fabric_version=0.92.1+1.20.1
